# Generated by Django 4.1 on 2022-10-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='stat',
            new_name='state',
        ),
    ]
